/// Test for the `lib/example/bookstore.dart` example. Wraps the
/// example in a test that asserts on the expected results.
library;

import 'package:d_rocket_engine_sqlite/d_rocket_engine_sqlite.dart';
import 'package:test/test.dart';

import '../example/bookstore.dart';
import '../example/d_rocket_registry.g.dart';

void main() {
  setUp(dRocketSqlite);
  tearDown(EngineRegistry.resetForTest);

  late BookstoreResults r;

  setUp(() {
    initializeD(); // Generated by d_rocket_builder. Registers
    // every `extends Record` class in this package.
    r = runBookstoreExample();
  });

  test('Q1: where_ — books published after 1970', () {
    expect(r.modernBooks.map((Book b) => b.id), [6]);
    expect(r.modernBooks.single.title, 'Love in the Time of Cholera');
  });

  test('Q2: orderByDescending_ + take_ — 3 most expensive books', () {
    expect(r.top3ByPrice.map((Book b) => b.id), [5, 6, 2]);
    expect(r.top3ByPrice.map((Book b) => b.price), [18.00, 15.50, 14.00]);
  });

  test('Q3: select_<String> — list of all titles', () {
    expect(r.allTitles, [
      'A Wizard of Earthsea',
      'The Left Hand of Darkness',
      'Foundation',
      'I, Robot',
      'One Hundred Years of Solitude',
      'Love in the Time of Cholera',
      'Ficciones',
    ]);
  });

  test('Q4: count_ — number of sales', () {
    expect(r.totalSales, 5);
  });

  test('Q5: sum_ — total revenue', () {
    // 12.50 + 19.98 + 14.00 + 18.00 + 25.50 = 89.98
    expect(r.totalRevenue, closeTo(89.98, 0.001));
  });

  test('Q6: average_ — average book price', () {
    // (12.50 + 14.00 + 9.99 + 8.50 + 18.00 + 15.50 + 11.25) / 7
    // = 89.74 / 7 ≈ 12.82
    expect(r.avgPrice, closeTo(89.74 / 7, 0.01));
  });

  test('Q7: min_ — oldest publication year', () {
    expect(r.minYear, 1944);
  });

  test('Q8: max_ — most expensive book price', () {
    expect(r.maxPrice, 18.00);
  });

  test('Q9: join_ — sci-fi book:author pairs', () {
    // sci-fi books: id 2, 3, 4. Author of each: Le Guin (1),
    // Asimov (2), Asimov (2).
    expect(r.sciFiPairs, [
      'Ursula K. Le Guin: The Left Hand of Darkness',
      'Isaac Asimov: Foundation',
      'Isaac Asimov: I, Robot',
    ]);
  });

  test('Q10: groupBy_ — books per author', () {
    // Author 1 (Le Guin): 2 books; 2 (Asimov): 2; 3 (García M): 2;
    // 4 (Borges): 1.
    expect(r.authorBookCounts, {1: 2, 2: 2, 3: 2, 4: 1});
  });

  test('Q11: groupJoin_ — every author with their books', () {
    // 4 authors, in the order of the seed (1, 2, 3, 4).
    expect(r.booksWithAuthors.length, 4);
    expect(r.booksWithAuthors[0], contains('Ursula K. Le Guin'));
    expect(r.booksWithAuthors[0], contains('A Wizard of Earthsea'));
    expect(r.booksWithAuthors[0], contains('The Left Hand of Darkness'));
    expect(r.booksWithAuthors[1], contains('Isaac Asimov'));
    expect(r.booksWithAuthors[1], contains('Foundation'));
    expect(r.booksWithAuthors[1], contains('I, Robot'));
    expect(r.booksWithAuthors[2], contains('Gabriel García Márquez'));
    expect(r.booksWithAuthors[2], contains('One Hundred Years of Solitude'));
    expect(r.booksWithAuthors[2], contains('Love in the Time of Cholera'));
    expect(r.booksWithAuthors[3], contains('Jorge Luis Borges'));
    expect(r.booksWithAuthors[3], contains('Ficciones'));
  });
}
