// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Generated by d_rocket_builder:record_registry.
// Source: every `extends Record`, `@Serializable`,
// `@RestClient`, and `@Table` class in lib/**.dart.
//
// Call [initializeD] once at application startup:
//
//   import "d_rocket_registry.g.dart";
//   void main() {
//     initializeD();
//     runApp(const MyApp());
//   }

import 'package:d_rocket_engine_sqlite/d_rocket_engine_sqlite.dart';
import 'bookstore.dart' as _m0;

bool _dRocketInitialized = false;

/// Initialize all d_rocket-managed classes in this
/// package. Call this once at application startup,
/// typically in `main()`.
///
/// Registers, in order:
/// 1. Field accessors for every `extends Record`
///    class (enables the debug-friendly `toString` and
///    the LINQ `MemberAccess` evaluator).
/// 2. `fromJson` / `toJson` pairs for every
///    `@Serializable` class (enables
///    `Serializer.fromJson<T>(...)` dispatch).
/// 3. `_<ClassName>.create` factories for every
///    `@RestClient` class (enables
///    `dRest.get<TodoApi>()` dispatch).
/// 4. `static EntityMeta entityMeta` for every
///    `@Table` class (enables
///    `DbSet<T>.add / SaveChanges()` SQL generation).
///
/// Idempotent: subsequent calls are no-ops.
void initializeD() {
  if (_dRocketInitialized) return;
  _dRocketInitialized = true;
  // Make sure the REST runtime is initialised before
  // any client factory tries to use it. Calling
  // `useDefaults` is a no-op if the consumer has
  // already configured `dRest` themselves.
  dRest.useDefaults();
  _m0.registerAuthorRecord();
  _m0.registerBookRecord();
  _m0.registerSaleRecord();
}
